name: Private ISU bench
run-name: Private ISU bench
on: push
defaults:
  run:
    shell: bash
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker
        run: |
          echo "::group::Docker version"
          docker --version
          echo "::endgroup::"

          echo "::group::Docker compose version"
          docker compose --version
          echo "::endgroup::"

      - name: Make
        run: |
          make init
          cd webapp/sql
          bunzip2 dump.sql.bz2
          cd ../..

      - name: Up Web
        run: |
          docker compose up -d

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install bench
        run: |
          cd benchmarker
          make all

      - name: Run bench
        run: bin/benchmarker -t http://localhost -u ./userdata 
    

