name: Private ISU bench
run-name: Private ISU bench
on: push
defaults:
  run:
    shell: bash
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker
        run: |
          echo "::group::Docker version"
          docker --version
          echo "::endgroup::"

          echo "::group::Docker compose version"
          docker compose version
          echo "::endgroup::"

      - name: Restore SQL dump
        id: restore-sql-dump
        uses: actions/cache@v4
        with:
          key: webapp-sql-dump
          path: webapp/sql/dump.sql
      
      - name: Fetch SQL dump
        if: steps.restore-sql-dump.outputs.cache-hit != 'true'
        run: |
          echo "::group::Make Fetch SQL dump"
          make webapp/sql/dump.sql.bz2
          echo "::endgroup::"

          cd webapp/sql
          bunzip2 dump.sql.bz2
          cd ../..

      - name: Cache SQL Dump
        uses: actions/cache/save@v4
        if: steps.restore-sql-dump.outputs.cache-hit != 'true'
        with:
          key: webapp-sql-dump
          path: webapp/sql/dump.sql

      - name: Restore Images
        id: restore-images
        uses: actions/cache@v4
        with:
          key: benchmarker-userdata-img
          path: benchmarker/userdata/img

      - name: Fetch Images
        if: steps.restore-images.outputs.cache-hit != 'true'
        run: |
          if [ -d benchmarker/userdata/img ]; then
            echo "Images already exists"
            exit 0
          fi

          echo "::group::Make Fetch Images"
          make benchmarker/userdata/img
          echo "::endgroup::"

      - name: Cache Images
        if: steps.restore-images.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: benchmarker-userdata-img
          path: benchmarker/userdata/img

      - name: Up Web
        run: |
          cd webapp
          
          echo "::group::Docker compose up"
          docker compose up -d
          echo "::endgroup::"

          cd ..

      - name: Check Web
        run: |
          echo "::group::Check Web"
          curl -I http://localhost
          echo "::endgroup::"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install bench
        run: |
          cd benchmarker

          echo "::group::Make All"
          make all
          chmod +x bin/benchmarker
          echo "::endgroup::"

          echo "::group::Install Check"
          ls
          ls bin
          echo "::endgroup::"

          bin/benchmarker -t http://localhost -u ./userdata 

      - name: Run bench
        run: |
          pwd
          bin/benchmarker -t http://localhost -u ./userdata 
    

